apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-flask-chart.fullname" . }}-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: {{ include "my-flask-chart.name" . }}
